<?php
$sallesVoies =['VERTICAL\'ART','CLIMB UP LYON CONFLUENCE','CLIMB UP LYON GERLAND', 'HOLD\'UP ESCALADE', 'ESPACE ESALADE A L\'ARBRESLE' ];
$sallesBloc =['MROC LAENNEC','MROC PART-DIEU','MROC VILLEURBANNE'];